version: '3'

services:

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs

volumes:

  logs:
    driver: local

networks:

  default:
    driver: bridge
